configure RUM and dd tracing on checkout

diff --git a/.github/workflows/component-build-images.yml b/.github/workflows/component-build-images.yml
--- a/.github/workflows/component-build-images.yml
+++ b/.github/workflows/component-build-images.yml
@@ -2,32 +2,25 @@
 # SPDX-License-Identifier: Apache-2.0
 
 on:
-  workflow_call:
-    inputs:
-      push:
-        description: Should the images be pushed
-        default: false
-        required: false
-        type: boolean
-      version:
-        description: The version used when tagging the image
-        default: 'dev'
-        required: false
-        type: string
-      dockerhub_repo:
-        description: Docker Hub repository
-        default: 'otel/demo'
-        required: false
-        type: string
-      ghcr_repo:
-        description: GHCR repository
-        default: 'ghcr.io/open-telemetry/demo'
-        required: false
-        type: string
+  push:
+    tags:
+      - "*"
 
 jobs:
+  protobufcheck:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+      - name: Generate
+        run: make clean docker-generate-protobuf
+      - name: Check Clean Work Tree
+        run: make check-clean-work-tree
+
   build_and_push_images:
     runs-on: ubuntu-latest
+    needs: protobufcheck
+
     permissions:
       contents: read
       packages: write
@@ -39,91 +32,102 @@ jobs:
       fail-fast: false
       matrix:
         file_tag:
-          - file: ./src/accountingservice/Dockerfile
-            tag_suffix: accountingservice
-            context: ./
-            setup-qemu: true
-          - file: ./src/adservice/Dockerfile
-            tag_suffix: adservice
-            context: ./
-            setup-qemu: true
-          - file: ./src/cartservice/src/Dockerfile
-            tag_suffix: cartservice
-            context: ./
-            setup-qemu: false
+          # - file: ./src/accountingservice/Dockerfile
+          #   tag_suffix: accountingservice
+          #   context: ./
+          #   setup-qemu: true
+          # - file: ./src/adservice/Dockerfile
+          #   tag_suffix: adservice
+          #   context: ./
+          #   setup-qemu: true
+          # - file: ./src/cartservice/src/Dockerfile
+          #   tag_suffix: cartservice
+          #   context: ./
+          #   setup-qemu: false
           - file: ./src/checkoutservice/Dockerfile
             tag_suffix: checkoutservice
             context: ./
             setup-qemu: true
-          - file: ./src/currencyservice/Dockerfile
-            tag_suffix: currencyservice
-            context: ./
-            setup-qemu: true
-          - file: ./src/emailservice/Dockerfile
-            tag_suffix: emailservice
-            context: ./
-            setup-qemu: true
-          - file: ./src/frauddetectionservice/Dockerfile
-            tag_suffix: frauddetectionservice
-            context: ./
-            setup-qemu: true
+          # - file: ./src/currencyservice/Dockerfile
+          #   tag_suffix: currencyservice
+          #   context: ./
+          #   setup-qemu: true
+          # - file: ./src/emailservice/Dockerfile
+          #   tag_suffix: emailservice
+          #   context: ./
+          #   setup-qemu: true
+          # - file: ./src/frauddetectionservice/Dockerfile
+          #   tag_suffix: frauddetectionservice
+          #   context: ./
+          #   setup-qemu: true
           - file: ./src/frontend/Dockerfile
             tag_suffix: frontend
             context: ./
             setup-qemu: true
-          - file: ./src/frontendproxy/Dockerfile
-            tag_suffix: frontendproxy
-            context: ./
-            setup-qemu: true
-          - file: ./src/frontend/Dockerfile.cypress
-            tag_suffix: frontend-tests
-            context: ./
-            setup-qemu: true
-          - file: ./src/imageprovider/Dockerfile
-            tag_suffix: imageprovider
-            context: ./
-            setup-qemu: true
-          - file: ./src/kafka/Dockerfile
-            tag_suffix: kafka
-            context: ./
-            setup-qemu: true
-          - file: ./src/loadgenerator/Dockerfile
-            tag_suffix: loadgenerator
-            context: ./
-            setup-qemu: true
-          - file: ./src/paymentservice/Dockerfile
-            tag_suffix: paymentservice
-            context: ./
-            setup-qemu: true
-          - file: ./src/productcatalogservice/Dockerfile
-            tag_suffix: productcatalogservice
-            context: ./
-            setup-qemu: true
-          - file: ./src/quoteservice/Dockerfile
-            tag_suffix: quoteservice
-            context: ./
-            setup-qemu: true
-          - file: ./src/recommendationservice/Dockerfile
-            tag_suffix: recommendationservice
-            context: ./
-            setup-qemu: true
-          - file: ./src/shippingservice/Dockerfile
-            tag_suffix: shippingservice
-            context: ./
-            setup-qemu: true
-          - file: ./src/flagd-ui/Dockerfile
-            tag_suffix: flagdui
-            context: ./
-            setup-qemu: true
-          - file: ./test/tracetesting/Dockerfile
-            tag_suffix: traceBasedTests
-            context: ./
-            setup-qemu: true
+          # - file: ./src/frontendproxy/Dockerfile
+          #   tag_suffix: frontendproxy
+          #   context: ./
+          #   setup-qemu: true
+          # - file: ./src/frontend/Dockerfile.cypress
+          #   tag_suffix: frontend-tests
+          #   context: ./
+          #   setup-qemu: true
+          # - file: ./src/imageprovider/Dockerfile
+          #   tag_suffix: imageprovider
+          #   context: ./
+          #   setup-qemu: true
+          # - file: ./src/kafka/Dockerfile
+          #   tag_suffix: kafka
+          #   context: ./
+          #   setup-qemu: true
+          # - file: ./src/loadgenerator/Dockerfile
+          #   tag_suffix: loadgenerator
+          #   context: ./
+          #   setup-qemu: true
+          # - file: ./src/paymentservice/Dockerfile
+          #   tag_suffix: paymentservice
+          #   context: ./
+          #   setup-qemu: true
+          # - file: ./src/productcatalogservice/Dockerfile
+          #   tag_suffix: productcatalogservice
+          #   context: ./
+          #   setup-qemu: true
+          # - file: ./src/quoteservice/Dockerfile
+          #   tag_suffix: quoteservice
+          #   context: ./
+          #   setup-qemu: true
+          # - file: ./src/recommendationservice/Dockerfile
+          #   tag_suffix: recommendationservice
+          #   context: ./
+          #   setup-qemu: true
+          # - file: ./src/shippingservice/Dockerfile
+          #   tag_suffix: shippingservice
+          #   context: ./
+          #   setup-qemu: true
+          # - file: ./src/flagd-ui/Dockerfile
+          #   tag_suffix: flagdui
+          #   context: ./
+          #   setup-qemu: true
+          # - file: ./test/tracetesting/Dockerfile
+          #   tag_suffix: traceBasedTests
+          #   context: ./
+          #   setup-qemu: true
 
     steps:
       - uses: actions/checkout@v4
         with:
           fetch-depth: 0
+      - name: Load environment variables from .env file
+        run: |
+          if [ -f .env ]; then
+            # Filter out comments and empty lines, then add each variable to $GITHUB_ENV
+            grep -vE '^\s*#|^\s*$' .env | while read -r line; do
+              echo "$line" >> $GITHUB_ENV
+            done
+          else
+            echo ".env file not found!"
+            exit 1
+          fi
       - name: Check for changes and set push options
         id: check_changes
         run: |
@@ -146,13 +150,6 @@ jobs:
           registry: ghcr.io
           username: ${{ github.repository_owner }}
           password: ${{ secrets.GITHUB_TOKEN }}
-        if: ${{ inputs.push }}
-      - name: Log in to Docker Hub
-        uses: docker/login-action@v3
-        with:
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_PASSWORD }}
-        if: ${{ inputs.push }}
       - name: Set up QEMU
         if: ${{ matrix.file_tag.setup-qemu }}
         uses: docker/setup-qemu-action@v3
@@ -165,17 +162,18 @@ jobs:
             [worker.oci]
             max-parallelism = 2
       - name: Matrix Build and push demo images
-        if: steps.check_changes.outputs.skip == 'false'
-        uses: docker/build-push-action@v6.9.0
+        uses: docker/build-push-action@v6.15.0
         with:
           context: ${{ matrix.file_tag.context }}
           file: ${{ matrix.file_tag.file }}
           platforms: linux/amd64,linux/arm64
-          push: ${{ inputs.push }}
+          push: true
+          build-args: |
+            OTEL_JAVA_AGENT_VERSION=${{ env.OTEL_JAVA_AGENT_VERSION }}
+            OPENTELEMETRY_CPP_VERSION=${{ env.OPENTELEMETRY_CPP_VERSION }}
+            TRACETEST_IMAGE_VERSION=${{ env.TRACETEST_IMAGE_VERSION }}
           tags: |
-            ${{ inputs.dockerhub_repo }}:${{ inputs.version }}-${{matrix.file_tag.tag_suffix }}
-            ${{ inputs.dockerhub_repo }}:latest-${{matrix.file_tag.tag_suffix }}
-            ${{ inputs.ghcr_repo }}:${{ inputs.version }}-${{ matrix.file_tag.tag_suffix }}
-            ${{ inputs.ghcr_repo }}:latest-${{ matrix.file_tag.tag_suffix }}
+            ghcr.io/abruneau/opentelemetry-demo:${{  github.ref_name }}-${{ matrix.file_tag.tag_suffix }}
+            ghcr.io/abruneau/opentelemetry-demo:latest-${{ matrix.file_tag.tag_suffix }}
           cache-from: type=gha
           cache-to: type=gha
